# Generated by Django 4.2.5 on 2023-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_options_alter_robot_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
