# Generated by Django 4.2.5 on 2023-09-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='robot_serial',
            field=models.CharField(max_length=5, verbose_name='Модель для заказа'),
        ),
    ]
